openapi: 3.0.3
info:
  title: Authentication API
  description: API for user authentication and JWT-based authorization
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of tasks for the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id
    post:
      summary: Create a new task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get task details
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to retrieve
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id
        '404':
          description: Task not found within user's scope
    put:
      summary: Update a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to update
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id
        '404':
          description: Task not found within user's scope
    delete:
      summary: Delete a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to delete
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id
        '404':
          description: Task not found within user's scope

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to update
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task to toggle
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - JWT user doesn't match URL user_id
        '404':
          description: Task not found within user's scope

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Optional description of the task
        completed:
          type: boolean
          description: Whether the task is completed
        user_id:
          type: string
          description: ID of the user who owns this task
        created_at:
          type: string
          format: date-time
          description: When the task was created
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Optional description of the task

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: New title of the task
        description:
          type: string
          description: New description of the task
        completed:
          type: boolean
          description: New completion status of the task