# API Contract: Tasks REST API

## OpenAPI Specification

```yaml
openapi: 3.0.3
info:
  title: Tasks API
  description: REST API for managing user tasks with authentication and user isolation
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 1
        user_id:
          type: integer
          description: ID of the user who owns this task
          example: 123
        title:
          type: string
          maxLength: 255
          minLength: 1
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Need to buy milk, bread, and eggs"
        completed:
          type: boolean
          description: Completion status of the task
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
          example: "2023-10-20T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last modified
          example: "2023-10-20T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Need to buy milk, bread, and eggs"
        completed:
          type: boolean
          description: Initial completion status of the task
          default: false
          example: false

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Need to buy milk, bread, and eggs"
        completed:
          type: boolean
          description: Completion status of the task
          example: false

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

  parameters:
    user_id:
      name: user_id
      in: path
      required: true
      schema:
        type: integer
      description: ID of the user whose tasks to access
      example: 123

    task_id:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: ID of the task to access
      example: 1

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      description: Retrieve a list of all tasks belonging to the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

    post:
      summary: Create a new task for a user
      description: Create a new task and associate it with the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request - Validation error in request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get task details
      description: Retrieve details of a specific task belonging to the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/task_id'
      responses:
        '200':
          description: Task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user or task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task with specified ID doesn't exist for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

    put:
      summary: Update a task
      description: Update details of a specific task belonging to the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/task_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request - Validation error in request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user or task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task with specified ID doesn't exist for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

    delete:
      summary: Delete a task
      description: Delete a specific task belonging to the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/task_id'
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user or task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task with specified ID doesn't exist for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a specific task belonging to the specified user
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/task_id'
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User ID in URL doesn't match authenticated user or task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task with specified ID doesn't exist for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
```